### ISSUE TITLE
Add CLI flags to support batch array job processing

### ISSUE THREAD

**Issue by benjeffery** [pystatgen/bio2zarr#71]
To distribute the work of `explode` and `endode` it would be useful to run commands such as:

`bio2zarr vcf2zarr explode --job 5 --total-jobs 50 INFILES OUTDIR`

Where the `--job` argument would be different on each worker.

Implementation wise I think this would mean breaking explode into 3 parts:

`explode start --total-jobs M` - single local task that does the scan and writes vcf partition metadata to the outdir
`explode write --job N` - parallel job for doing the conversion reads metadata from OUTDIR and writes partition summaries
`explode finalise` - single local job that writes the updated metadata, after reading the partition summaries, errors out if a partition summary is missing.

If none of these are specified then the usual explode proceeds locally as it does now.

**Comment by benjeffery** [comment]
I'm happy to pick this one up.

**Comment by jeromekelleher** [comment]
Let me have a think about this...

What would the corresponding snakemake look like?

Would it be simpler to expose this as Python functions, which Snakemake can hook into (and keep the CLI for interactive work)?

**Comment by benjeffery** [comment]
The snakemake would be quite straightforward:

```
rule all:
    input:
        f"{output_dir}/metadata.json"

rule explode_start:
    input:
        input_files=INFILES
    output:
        OUTDIR/partitions.json
    shell:
        """
        bio2zarr vcf2zarr explode start --total-jobs {total_jobs} {input_files} OUTDIR && touch {output}
        """

rule explode_write:
    input:
        OUTDIR/partitions.json
    output:
        flag=OUTDIR/job_{jobid}.flag
    params:
        total_jobs=total_jobs,
    shell:
        """
        bio2zarr vcf2zarr explode write --job {jobid} --total-jobs {params.total_jobs} INFILES OUTDIR && touch {output.flag}
        """

rule explode_finalize:
    input:
        expand(f"OURDIR/job_{{jobid}}.flag", jobid=range(0, total_jobs))
    output:
        OUTDIR/metadata.json
    shell:
        """
        bio2zarr vcf2zarr explode finalize INFILES OUTDIR
        """
```

I think we need both the python way and the CLI as for classic batch array submission a CLI way would be much simpler.

**Comment by jeromekelleher** [comment]
Fair enough... I'm just slightly queasy about adding another level of command hierarchy to the CLI.

**Comment by jeromekelleher** [comment]
In principle this is pretty straighforward. In the initial bit, we need to influence how many partitions we split the file into, and then save the metadata as ``wip.metadata.json`` (or something) around [here](https://github.com/pystatgen/bio2zarr/blob/35c62b0115a14876525fef33e4cbe78dd77a5388/bio2zarr/vcf.py#L964)

Then, there's the actual "explode" tasks, which take a slice of partition IDs starting [here](https://github.com/pystatgen/bio2zarr/blob/35c62b0115a14876525fef33e4cbe78dd77a5388/bio2zarr/vcf.py#L966) 
Each of the explode tasks first reads the metadata from ``wip.metadata.json``.

Then, once all the explode tasks are done, we just finalise by renaming  ``wip.metadata.json`` to ``metadata.json``.

From a UI perspective, this is then:
```
bio2zarr explode-init  <vcfs> <destdir> [num partitions]
```
Splits into N partitions, writes ```wip.metadata.json`` (and header.txt) and exits

```
bio2zarr explode-slice <destdir> start stop
```
Assumes explode-init has already happened, and tries to explode the specified partition slice

```
bio2zarr explode-finalise <destdir> 
```

The ``explode`` command on its own just does these things sequentially.

I think that's better than more hierarchy?

**Comment by jeromekelleher** [comment]
Ah, it's not that simple, we need to keep the summaries per partition. 


Let's just change the format to save the partition summaries as JSON, one per partition. This can be done as part of the work packet rather than being returned from the future. Then the finalise step reads these files, and saves the final metadata.json.

This is actually a good check that the partition has been fully completed too, so helps with integrity.

Good, I like this!

**Comment by jeromekelleher** [comment]
Snakemake can also use partition_j.json to flag whether partition j has completed too, right?

**Comment by benjeffery** [comment]
Thinking about the `num_partitions` being essentially unpredictable to exact number, I don't think we can have an upper bound. The number of partitions is dependant on contigs inside the VCF that aren't known before we scan. My current approach is to have a target number that the code aims for, but to write the actual number to a file that the snakemake can then read in to determine the jobs for the next step. This isn't ideal, but I can't see a way around this.

**Comment by jeromekelleher** [comment]
What about reading the metadata.wip.json or whatever? Should be easy to parse, or could provide a python API (or cli)?

**Comment by benjeffery** [comment]
I think a CLI that reads the json might work. I don't want the user to have to parse JSON if they are using bash etc.

**Comment by jeromekelleher** [comment]
Closing as completed (for explode)
