### ISSUE TITLE
Rename chunk_width to samples_chunk_size and chunk_length to variants_chunk_size (or similar)

### ISSUE THREAD

**Issue by jeromekelleher** [pystatgen/bio2zarr#73]
I find it unhelpful adding different dimensions here which don't actually line up with the named xarray dimensions. I think we should use the named dimensions here in some way, rather than "length" and "width".

Options:

- chunk_variants, chunk_samples
- variants_chunk_size, samples_chunk_size
- ...

I don't really know what's the best choice here.

Any thoughts @tomwhite @benjeffery?

**Comment by tomwhite** [comment]
+1 to changing the names. I vote for `variants_chunk_size` and `samples_chunk_size`.

**Comment by benjeffery** [comment]
Yep, agreed that the dimensions should be named

**Comment by jeromekelleher** [comment]
OK, ``variants_chunk_size`` and ``samples_chunk_size`` it is. Should be simple search and replace
